version: '2'
services:
  scoreboard:
    container_name: scoreboard
    build: .
    ports:
     - "80:8080"
    links:
     - mariadb
  mariadb:
    image: mariadb
    container_name: scoreboard-db
    environment:
      MYSQL_DATABASE: scoreboard
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
